import './globals.css'
// import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import Script from "next/script";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        
      <body >{children}</body>
      </html>
  )
}
